sandbox: false
credentials_file: credentials.cfg
product_list: [LTC-BTC, BTC-EUR, ETH-BTC, ETC-BTC, ETC-EUR, ETH-EUR, LTC-EUR, LINK-ETH]
brokers:
  - type: max_amount
    product_list: [LTC-BTC, BTC-EUR, ETH-BTC, ETC-BTC, ETC-EUR, ETH-EUR, LTC-EUR, LINK-ETH]